from __future__ import annotations

"""
Hard-coded plan → features mapping.

This replaces loading the Plan <> FF matrix from files/Sheets.
You can still override via the app’s “Manual Plan JSON (override)” section.
"""

from typing import Dict, List


# Nested family → plan → features, as provided
NESTED_PLAN_JSON: Dict[str, dict | list] = {
    "Shipowners": {
        "Shipowners Core": [
            "hideRuleEngine",
            "complianceMode",
            "weatherLayer",
            "liveChat",
            "complianceLabel",
            "sendHeartbeat",
            "portStateControl",
            "userAlreadyLoggedInWarning",
            "hideSafetyRisk",
            "hideBorderSecurityRisk",
            "hideMapModule",
            "portProfile",
        ],
        "Shipowners Advanced": [
            "hideRuleEngine",
            "complianceMode",
            "weatherLayer",
            "liveChat",
            "complianceLabel",
            "sendHeartbeat",
            "savedQueriesNotifications",
            "portStateControl",
            "userAlreadyLoggedInWarning",
            "advancedSearchOwners",
            "hideSafetyRisk",
            "hideBorderSecurityRisk",
            "mapMarkers",
            "nasAddVesselsToVoi",
            "nasTransmissionInAreaActivityType",
            "newNasSideBarDesign",
            "portProfile",
            "companyProfile",
            "exploreCompanies",
            "enableExportCompanyPdfReport",
            "maiExpertVesselSummary",
            "maiExpertVesselAdverseMedia",
        ],
        "Shipowners Premium": [
            "hideRuleEngine",
            "complianceMode",
            "liveChat",
            "complianceLabel",
            "newAdvancedSearch",
            "sendHeartbeat",
            "savedQueriesNotifications",
            "portStateControl",
            "userAlreadyLoggedInWarning",
            "advancedSearchOwners",
            "hideSafetyRisk",
            "hideBorderSecurityRisk",
            "companyProfile",
            "exploreCompanies",
            "enableExportCompanyPdfReport",
            "mapMarkers",
            "nasAddVesselsToVoi",
            "nasTransmissionInAreaActivityType",
            "newNasSideBarDesign",
            "portProfile",
            "maiExpertVesselSummary",
            "maiExpertVesselAdverseMedia",
            "uboData",
            "weatherLayer",
            "newNotificationUI",
            "wetCargoData",
        ],
    },
    "Bunkering": {
        "Bunkering Core": [
            "hideRuleEngine",
            "complianceMode",
            "weatherLayer",
            "liveChat",
            "complianceLabel",
            "sendHeartbeat",
            "portStateControl",
            "userAlreadyLoggedInWarning",
            "hideSafetyRisk",
            "hideBorderSecurityRisk",
            "hideMapModule",
            "stsClassification",
            "portProfile",
        ],
        "Bunkering Advanced": [
            "hideRuleEngine",
            "complianceMode",
            "weatherLayer",
            "liveChat",
            "complianceLabel",
            "sendHeartbeat",
            "savedQueriesNotifications",
            "portStateControl",
            "userAlreadyLoggedInWarning",
            "advancedSearchOwners",
            "hideSafetyRisk",
            "hideBorderSecurityRisk",
            "mapMarkers",
            "nasAddVesselsToVoi",
            "nasTransmissionInAreaActivityType",
            "newNasSideBarDesign",
            "hideMapModule",
            "companyProfile",
            "exploreCompanies",
            "enableExportCompanyPdfReport",
            "stsClassification",
            "cddScreening",
            "maiExpertVesselSummary",
            "maiExpertVesselAdverseMedia",
            "portProfile",
        ],
        "Bunkering Premium": [
            "hideRuleEngine",
            "complianceMode",
            "liveChat",
            "complianceLabel",
            "newAdvancedSearch",
            "sendHeartbeat",
            "savedQueriesNotifications",
            "portStateControl",
            "userAlreadyLoggedInWarning",
            "advancedSearchOwners",
            "hideSafetyRisk",
            "hideBorderSecurityRisk",
            "companyProfile",
            "exploreCompanies",
            "enableExportCompanyPdfReport",
            "mapMarkers",
            "nasAddVesselsToVoi",
            "nasTransmissionInAreaActivityType",
            "newNasSideBarDesign",
            "portProfile",
            "maiExpertVesselSummary",
            "maiExpertVesselAdverseMedia",
            "stsClassification",
            "weatherLayer",
            "cddScreening",
            "wetCargoData",
        ],
    },
    "Insurer": {
        "Insurer Core": [
            "hideRuleEngine",
            "complianceMode",
            "weatherLayer",
            "liveChat",
            "complianceLabel",
            "sendHeartbeat",
            "portStateControl",
            "userAlreadyLoggedInWarning",
            "hideSafetyRisk",
            "hideBorderSecurityRisk",
            "hideMapModule",
            "companyProfile",
            "exploreCompanies",
            "enableExportCompanyPdfReport",
            "portProfile",
        ],
        "Insurer Advanced": [
            "hideRuleEngine",
            "complianceMode",
            "weatherLayer",
            "liveChat",
            "complianceLabel",
            "sendHeartbeat",
            "portStateControl",
            "userAlreadyLoggedInWarning",
            "hideSafetyRisk",
            "hideBorderSecurityRisk",
            "companyProfile",
            "exploreCompanies",
            "enableExportCompanyPdfReport",
            "uboData",
            "portProfile",
            "maiExpertVesselSummary",
            "maiExpertVesselAdverseMedia",
        ],
        "Insurer Premium": [
            "hideRuleEngine",
            "complianceMode",
            "liveChat",
            "complianceLabel",
            "sendHeartbeat",
            "portStateControl",
            "userAlreadyLoggedInWarning",
            "VLA",
            "hideSafetyRisk",
            "hideBorderSecurityRisk",
            "companyProfile",
            "exploreCompanies",
            "enableExportCompanyPdfReport",
            "mapMarkers",
            "portProfile",
            "maiExpertVesselSummary",
            "maiExpertVesselAdverseMedia",
            "uboData",
            "weatherLayer",
            "cddScreening",
            "wetCargoData",
        ],
    },
    "Commodity Trader": {
        "Commodity Trader Core": [
            "hideRuleEngine",
            "complianceMode",
            "weatherLayer",
            "liveChat",
            "complianceLabel",
            "sendHeartbeat",
            "portStateControl",
            "userAlreadyLoggedInWarning",
            "hideSafetyRisk",
            "hideBorderSecurityRisk",
            "hideMapModule",
            "companyProfile",
            "exploreCompanies",
            "enableExportCompanyPdfReport",
            "portProfile",
        ],
        "Commodity Trader Advanced": [
            "hideRuleEngine",
            "complianceMode",
            "weatherLayer",
            "liveChat",
            "complianceLabel",
            "sendHeartbeat",
            "portStateControl",
            "userAlreadyLoggedInWarning",
            "hideSafetyRisk",
            "hideBorderSecurityRisk",
            "companyProfile",
            "exploreCompanies",
            "enableExportCompanyPdfReport",
            "uboData",
            "portProfile",
            "VLA",
            "maiExpertVesselSummary",
            "maiExpertVesselAdverseMedia",
        ],
        "Commodity Trader Premium": [
            "hideRuleEngine",
            "complianceMode",
            "liveChat",
            "complianceLabel",
            "sendHeartbeat",
            "portStateControl",
            "userAlreadyLoggedInWarning",
            "VLA",
            "hideSafetyRisk",
            "hideBorderSecurityRisk",
            "companyProfile",
            "exploreCompanies",
            "enableExportCompanyPdfReport",
            "mapMarkers",
            "portProfile",
            "maiExpertVesselSummary",
            "maiExpertVesselAdverseMedia",
            "uboData",
            "weatherLayer",
            "cddScreening",
            "wetCargoData",
        ],
    },
    "Custom": {
        "Custom": [
            "hideRuleEngine",
            "complianceMode",
            "liveChat",
            "complianceLabel",
            "sendHeartbeat",
            "portStateControl",
            "userAlreadyLoggedInWarning",
            "companyProfile",
            "exploreCompanies",
            "enableExportCompanyPdfReport",
            "portProfile",
            "savedQueriesNotifications",
            "hideMapTimelineOnVesselProfile",
            "nasAccidentsActivity",
            "newNasSideBarDesign",
            "nasAddVesselsToVoi",
            "shadowFleetVOIs",
            "weatherLayer",
            "nasPremiumCsvColumns",
        ]
    },
    "Financial Institutions": {
        "Financial Institutions Core": [
            "hideRuleEngine",
            "warRiskArea",
            "complianceMode",
            "softAoi",
            "liveChat",
            "complianceLabel",
            "sendHeartbeat",
            "portStateControl",
            "userAlreadyLoggedInWarning",
            "enableExportCompanyPdfReport",
            "companyProfile",
            "exploreCompanies",
            "portProfile",
            "savedQueriesNotifications",
            "hideSafetyRisk",
            "hideMapTimelineOnVesselProfile",
            "newNasSideBarDesign",
            "nasAccidentsActivity",
            "uboData",
            "shadowFleetVOIs",
            "weatherLayer",
        ],
        "Financial Institutions Advanced": [
            "hideRuleEngine",
            "warRiskArea",
            "nasAccidentsActivity",
            "complianceMode",
            "softAoi",
            "liveChat",
            "complianceLabel",
            "enableExportCompanyPdfReport",
            "sendHeartbeat",
            "portStateControl",
            "userAlreadyLoggedInWarning",
            "companyProfile",
            "exploreCompanies",
            "portProfile",
            "savedQueriesNotifications",
            "hideMapTimelineOnVesselProfile",
            "newNasSideBarDesign",
            "uboData",
            "maiExpertVesselSummary",
            "maiExpertVesselAdverseMedia",
            "shadowFleetVOIs",
            "nasAddVesselsToVoi",
            "VLA",
            "weatherLayer",
        ],
    },
    "EXTRAS": {
        "Extras": [
            "cddScreening",
            "wetCargoData",
            "uboData",
            "exportCenter",
            "newsFeed",
            "VLA",
            "stsClassification",
            "AgGrid",
            "nasPremiumCsvColumns",
            "underwaterCables",
        ]
    },
}


def get_flat_plan_json() -> Dict[str, List[str]]:
    """Flatten the nested structure into {plan: [features,...]}.

    - Ignores the EXTRAS family for the returned mapping.
    - Deduplicates and trims feature names.
    """
    flat: Dict[str, set] = {}
    for family, plans in NESTED_PLAN_JSON.items():
        if str(family).strip().upper() == "EXTRAS":
            continue
        if isinstance(plans, dict):
            for plan_name, feats in plans.items():
                if not isinstance(feats, list):
                    continue
                plan = str(plan_name).strip()
                for f in feats:
                    fs = str(f).strip()
                    if fs:
                        flat.setdefault(plan, set()).add(fs)
        elif isinstance(plans, list):
            # Treat family name as plan when value is a list
            plan = str(family).strip()
            for f in plans:
                fs = str(f).strip()
                if fs:
                    flat.setdefault(plan, set()).add(fs)
    return {k: sorted(list(v)) for k, v in flat.items()}

